export const VIDEOS = [
  { id: '4GUJ-tiG1Fc', title: 'Show Me Love (Dj \'\'S\'\' "New York Remix\'\')', artist: 'Robin Stone' },
  { id: 'BG_evU3-Sn8', title: 'It\'s Over Now (Hex Retro-Future Mix)', artist: '' },
  { id: '-b-6ksMdkrU', title: 'Fascinated', artist: 'Company B' },
  { id: 'B6dvFcziB0s', title: 'Body To Body', artist: 'Gepy & Gepy' },
  { id: 'vmvXT_W3sZ0', title: 'That\'s The Game', artist: 'Wet' },
  { id: 'HxwspItENz0', title: 'The Forest (Trentemoller Edit)', artist: 'The Cure vs Nina Simone' },
  { id: 'mfI1S0PKJR8', title: 'True Faith (1987)', artist: 'New Order' },
  { id: 'TvzVTRK1nOY', title: 'Hold Me Now', artist: 'Thompson Twins' },
  { id: 'FIF7wKJb2iU', title: 'Give Me The Night', artist: 'George Benson' },
  { id: 'Yf_Lwe6p-Cg', title: 'Everything She Wants', artist: 'Wham!' },
  { id: '5HI_xFQWiYU', title: 'The Promise', artist: 'When In Rome' },
  { id: 'EXMPYgja7hc', title: 'Just Can\'t Get Enough (rubber band mix)', artist: 'Depeche Mode' },
  { id: 'g1mdY5Biwfk', title: 'Terror (Original) [2002] [HQ]', artist: 'Fused' },
  { id: 'fx3AIK1EhnY', title: 'Where Have You Been (Peter Rauhofer Reconstruction Mix)', artist: 'Rihana' },
  { id: 'vaVMgZj_k_g', title: 'Another Day In Paradise (Phil Collins Cover Edit)', artist: 'Psychemagik' },
  { id: '9SoQoUlAZWE', title: 'Can\'t Get Enough', artist: 'Soulsearcher' },
  { id: 'tfr-h6BaYN8', title: 'Let It Happen (Soulwax Remix)', artist: 'Tame Impala' },
  { id: 'GcRRXxzvTTM', title: 'Back Home', artist: 'Anthony Rother' },
  { id: '46IQu0yuJzU', title: '\'Til I Die', artist: 'The Beach Boys' },
  { id: 'UCxjGsaEL_0', title: 'Lil\' Louis ‎-- Club Lonely (I\'m On The Guest List Mix)', artist: '' },
  { id: 'kxZD0VQvfqU', title: 'My Love Is Your Love (Official HD Video)', artist: 'Whitney Houston' },
  { id: 'IVmmyFZ6e1o', title: 'Music for Molly', artist: '' },
  { id: '5zPC5Vz2jAY', title: 'RnB Drunkie', artist: 'Mark E' },
  { id: 'mYI_hLYQ6-k', title: 'Justify My Love (Orbit Edit) [2022 Remaster]', artist: '' },
  { id: '9o0rAvZtM7w', title: 'Dirty Cash (Money Talks)', artist: 'Adventures Of Stevie V' },
  { id: 'ccNQ8-6IoH0', title: 'Pick Me Up Say Goodbye', artist: 'Al Kent' },
  { id: '9PWz-NubVpM', title: 'Wish I Didn\'t Miss You', artist: 'Angie Stone' },
  { id: 'UbTa5NccOus', title: 'Games People Play', artist: 'The Alan Parsons Project' },
  { id: 'ArhQZcUTkZU', title: 'Full Moon (Full Intention Club Mix)', artist: 'Brandy' },
  { id: 'pqwKUZJHZQE', title: 'I Wouldn\'t Change A Thing', artist: 'Coke Escovedo' },
  { id: 'ipBkUDPYaDo', title: 'Good Vibrations (Rhythm Stick Version)', artist: 'Marky Mark & The Funky Bunch' },
  { id: 'z722oHbNOLs', title: 'Good Vibrations (Ultimix Version)', artist: 'Marky Mark & The Funky Bunch' },
  { id: 'fiLJTttsIQ4', title: 'CAN\'T GET (VOCAL MIX)', artist: '' },
  { id: 'wT_BGcyarao', title: 'Show Me Su\'mn', artist: '' },
  { id: 'r7dSXwhKtS8', title: 'A Island Life', artist: '' },
  { id: 'gNbmPM3ztSg', title: 'Days Like This (K Klass Club Mix)', artist: '' },
  { id: 'lrKZNqIR2U0', title: 'Can You Feel It', artist: 'The Jacksons' },
  { id: 'h3ucycCzaXE', title: 'Sanctified', artist: 'E Versions #5' },
  { id: 'zAoczeDV4z0', title: 'Rumours', artist: 'Santos' },
  { id: 'ZYV6_NxyBJk', title: 'Touch of Magic (Epic Voyage)', artist: 'Dr. Packer' },
  { id: 'ubgQqvL93ao', title: 'Magazine', artist: 'E-Versions' },
  { id: 'f_mGMSYWzLU', title: 'Love To The World (Kon\'s Lots Of Love Remix)', artist: 'L.T.D.' },
  { id: 'RgW6bSnoMqA', title: 'Ghosts Dancing', artist: 'Gay Marvine' },
  { id: 'DSfjtdnUsls', title: 'Getting Away With It (1990 Official Music Video)', artist: 'Electronic' },
  { id: 'wnlXfsf86j8', title: 'I See The Light (Niles Cooper\'s Trommer & Bas Haus Miks)', artist: 'Crown Heights Affair' },
  { id: 'VHjl4bF2J3E', title: 'love (( slowed + reverb ))', artist: 'keyshia cole' },
  { id: 'KgsSPr_TmJM', title: 'You Make Me Feel (Mighty Real) [Jewels & Stone Mighty Nu Club Edit]', artist: 'Sylvester' },
  { id: 'CtrKJVPYNaQ', title: 'No Requests', artist: 'The Knocks' },
  { id: 'tmr3_Yb1k3c', title: 'Jaws (Extended Promo) MCXRMS', artist: 'Lalo Schiffrin' },
  { id: 'm4S_Z9I-R1g', title: 'You\'re In My System (Kerri Chandler Atmospheric Vocal) MCXRMS', artist: 'The System' },
  { id: 'Qi11LVYL8g4', title: 'Love Songs (Out Now on Body High)', artist: 'DJDS' },
  { id: 'kK-LW7iRDeo', title: 'Anikana [BONFIDO 002]', artist: 'Fixed Angles' },
  { id: 'xc-zwosPjn8', title: 'Footprints [Another Record Label]', artist: 'Premiere: Kaz James' },
  { id: 'UHFH47mRreE', title: 'Nobody\'s Business (Main Vocal)', artist: 'H2O featuring Billie' },
  { id: 'ZFl6P-XaEbA', title: 'HERBERT LEONARD Chante Avec Moi (@YoungPulse Edit)', artist: '' },
  { id: 'Q6Ry8G_Y3wg', title: '7 Days in the Hotel (M-High Remix)', artist: 'KOKO' },
  { id: 'LClBLELPtzU', title: 'Be free (Emmaculate & Shannon Chamber extended mix)', artist: 'Ten City' },
  { id: 'oc4JIb3fZnY', title: 'Make Me Feel', artist: 'Marc Cotterell' },
  { id: 'UX73RJGyE-0', title: 'A Ka Titine (Dam Swindle Edit)', artist: 'Gaoulé Mizik' },
  { id: 'aowZsSGBRLc', title: 'Rufus and Chaka Khan, Do You Love What You Feel, (Voc Tim Mix DDRM)', artist: '' },
  { id: 'hC-vopsSiLo', title: 'Seal, Love (VOX 1)', artist: '' },
  { id: 'iOIXhs8Oq9k', title: 'Mary J. Blige, Good Morning Gorgeous, Terry Hunter, DJ Spen, Reelsoul Remix (Unreleased)', artist: '' },
  { id: '6Z_1eYVgwXM', title: 'Kate Nash, Nicest thing (Ck In The Remix)', artist: '' },
  { id: 'AMpRpLDKrP0', title: 'Mentirosa (Koichi Toyama Edit)', artist: '' },
  { id: 'j-5lYGGratc', title: 'It\'s Not Madonna (Rescue Me)', artist: 'Tough As Old Boots' },
  { id: 'afehkcDbLtA', title: 'Gepy & Gepy, "Body To Body"  [RAI, 1979]', artist: 'Discomare' },
  { id: 'g1uZkgr2gHY', title: '17 Days (Piano & A Microphone 1983 Version)', artist: '' },
  { id: 'FQZDBoeJ7Pg', title: 'Ain\'t Nobody (Late Night Tuff Guy Rework)', artist: 'Rufus and Chaka Khan' },
  { id: 'vptVX5IrD7U', title: 'Ain\'t Nobody (Frankie Knuckles Remix)', artist: 'Rufus & Chaka Khan' },
  { id: '--FVIyvN83E', title: 'B-52\'s: "MESOPOTAMIA" [J*ski Extended]', artist: '' },
  { id: 'kVxE33w20Y4', title: 'White Rabbit  V\'s Into The Hole Edit', artist: 'Aifferson J Plain' },
  { id: '6lPGQ45w46Q', title: 'Dare Edit || Self-Released || 2023', artist: 'OSSX' },
  { id: 'I5OGLG0WJbM', title: 'Dreamlover (Def Club Mix - Official Audio)', artist: 'Mariah Carey' },
  { id: 'vxceCsEtMCg', title: 'Stomp! (Album Version) HQ', artist: 'THE BROTHERS JOHNSON' },
  { id: '7ebrhVYPJb8', title: 'Stylo (Alex Metric Remix)', artist: 'Gorillaz' },
  { id: 'AERnLwMoyFA', title: 'Love (Old Nick edit)', artist: 'Keyshia Cole' },
  { id: 'uRH8kP-zOZg', title: 'Always Be My Baby (Always Club Mix - Official Audio)', artist: 'Mariah Carey' },
  { id: 'kx8uaDRbgTU', title: 'Fuck Me Right feat  DJ Funk & Vula  Dub Mix', artist: 'Riton presents Gucci Soundsystem' },
  { id: '6xD7YhdzmIc', title: 'Teardrops (Rules Remix)', artist: 'Womack & Womack' },
  { id: 'SIMTpE7wqUw', title: 'Teardrops (Lovestation Classic 12" Mix)', artist: '' },
  { id: 'ghsSnD8zKGE', title: 'Fantasy (Def Club Mix) [David Morales] *Oldskool House*', artist: 'Mariah Carey' },
  { id: 'kNNEO7eSTOo', title: 'Heat You Up (Melt You Down) (Medlar Extended Edit)', artist: 'Shirley Lites' },
  { id: 'mfpLKAhw1J8', title: 'Heat You Up (Melt You Down)', artist: 'Shirley Lites' },
  { id: 'iJ7JtFKZzVo', title: 'A Part of You', artist: '' },
  { id: 'yQpHCs5OkpI', title: 'DREAMS CAN COME TRUE', artist: 'BEFORE MOSES' },
  { id: 'rRlj0LUBM1I', title: 'Neil "Hawaiin" House & "Spinnin\' Wheel" Bill | All Over', artist: '' },
  { id: 'CnNM5iMa3IA', title: 'BACK IN TIME [FLIPSIGHT]', artist: 'RICKY RAZU' },
  { id: 'YOZlitvuGvw', title: 'GOT TO BE LARGE [STUDIO 45]', artist: 'DEL GAZEEBO' },
  { id: 'ImJBBaJBat4', title: 'ON THE WORD [GAMM RECORDS]', artist: 'UKOKOS & JABCO' },
  { id: '7ZhnHeyMNGg', title: 'Emancipate Yourself', artist: 'Niles Cooper' },
  { id: 'gg6Hu3CN-pM', title: 'BLESSED ARE THE MEEK (JUST JACK RECORDINGS)', artist: 'UNKNOWN ARTIST' },
  { id: 'USQhqHG2pDE', title: 'RC GROOVE', artist: 'EVENN' },
  { id: 'HuxfT4EdTuI', title: 'CHERRIES (ESUOH WHITE 003)', artist: 'TOM JAY' },
  { id: 'LXjSOy38Vb8', title: 'UNTITLED TRACK 1 [RAKIJA 005]', artist: 'UNKNOWN ARTIST' },
  { id: 'JSpFtAIMkiY', title: 'PHANTOM JAM [ENDZ 050]', artist: 'SIDNEY CHARLES' },
  { id: 'iQ8jcNx2f-U', title: 'FEELIN\' IT [NU GROOVE]', artist: 'JAMIE 3:26' },
  { id: 'ko8cJucsbBU', title: 'EMOTINIUM', artist: 'Roy of the Ravers' },
  { id: '4ZlC5OT08JE', title: 'TAKE ME BACK', artist: 'DJOKO' },
  { id: 'mJCkIB3--5c', title: 'HOUSE HAS TAKEN OVER ME [MASLOW UNKNOWN EDIT]', artist: '' },
  { id: 'o2j2WZnOlNE', title: 'TRACK ID1 (Feat. RITA MDN - KERRI CHANDLER REMIX)', artist: 'MR ID & YOUSSEF GRIRANE' },
  { id: 'EEv5wbTQBCA', title: 'MAD QUEEN [M​.​A​.​D EDITS 001]', artist: 'MAKE A DANCE' },
  { id: 'V5vCp50FCGM', title: 'RAIN [MILLION DOLLAR DISCO]', artist: 'AL KENT' },
  { id: 'ugEZRY-ZRpM', title: 'NEVER THE SAME [STEEL CITY DANCE DISCS]', artist: 'LOODS' },
  { id: 'EGa9mR34EWw', title: 'WHEN LOVE IS TENDER (SWEET MIX) [PHONICA WHITE]', artist: 'AUSTIN ATO' },
  { id: 'sw7uMD4IqD0', title: 'FINDAWAY2DAY [PHONICA RECORDS]', artist: 'ELI ESCOBAR' },
  { id: 'guiKze3z6pI', title: 'AFFAIRS (SIGGATUNEZ\' LIVE EDIT) [DOODLEGZ #1]', artist: '' },
  { id: 'abafSAu-JG8', title: 'CAN\'T STOP', artist: 'UNKNOWN ARTIST' },
  { id: 'KmEc4j_BJLI', title: 'PURE VIBES', artist: 'MORE & MORE' },
  { id: '7cY5OTaFYo8', title: 'LOOP SOUP [MATE 008]', artist: 'GARRETT DAVID' },
  { id: 'c_WKiwecz50', title: 'POPPA [ODD NUMBERS]', artist: 'CAB' },
  { id: 'oD9dBY71Lkw', title: 'only time will tell (smack intime somewhere mix 1992', artist: 'ten city' },
  { id: 'GPuk_Cpmidg', title: 'Say Something (John Robinson Classic mix)', artist: 'Ten City' },
  { id: 'uvzJ-3yCto0', title: 'Operator (DJ Koze\'s Extended Disco Version)', artist: 'Låpsley' },
  { id: 'sukhjDEx5_M', title: 'D_K_Y (BUT I DO) (SULTA SELECTS 3)', artist: 'DENIS SULTA' },
  { id: 'd0Pr0AHfgOA', title: 'There Must Be Love (World Mix)', artist: '' },
  { id: 'nIo2vVcQXYU', title: 'David Morales & Janice Robinson // There Must Be Love (World Radio Mix)', artist: '' },
  { id: 'JOty4FEipQg', title: 'Together Again (Tony Humphries Club Mix)', artist: '' },
  { id: 'PdsyZStFlG8', title: 'Phreaky M.F. (Mike Dunn\'s Original Phreak Mixx)', artist: 'Mike Dunn, Mr. 69' },
  { id: 'KPpciYTd4I4', title: 'Teardrops (feat. Michelle Martinez)', artist: '' },
  { id: 'jd9t1LWWAd4', title: 'Magalenha (Perko\'s Firecracker Mix) [Schvitz Edits]', artist: 'PREMIERE: S. Mendes' },
  { id: 'J_GdMRk07TU', title: 'Magalenha', artist: 'Simon Fava & Gregor Salto feat. Sergio Mendes' },
  { id: 'N3kkNfH4yco', title: 'The Weekend', artist: 'Michael Gray' },
  { id: 'CYX9H0QSVTE', title: 'REMINISCE [UNO CLIO MIX]', artist: 'M J B' },
  { id: 'xHeBN4Ndc8s', title: 'FEELIN\' FEELIN\'', artist: 'INAYA DAY' },
  { id: 'FwXskdcCRIk', title: 'Beachball (Extended Vocal Mix)', artist: 'Nalin & Kane' },
  { id: '-zNK1iNNk3c', title: 'Let Love Enter (Remix)(2005)', artist: 'Stacy Kidd' },
  { id: 'QdbvR9fEQm0', title: 'Janet Jackson: If [Brothers In Rhythm House Mix]', artist: '' },
  { id: 'ZHukACYUTQ8', title: 'Heaven (Gerd Janson & Shan Edit)', artist: 'Gibson Brothers' },
  { id: 'pE0oDsGkd4s', title: 'Christy Essien   You Can\'t Change A Man   1979', artist: '' },
  { id: 'a_Y5k5t-rGw', title: 'U Sure Do (Guest List Mix)', artist: 'Strike' },
  { id: 'FWvOvfgU4bI', title: 'Gemini \'In My Head\' (Freaks Move This Way Vocal Dubby)', artist: '' },
  { id: 'y7DOSuSjyQE', title: 'Madonna Causing A Commotion (Co-ted\'s Mix)', artist: '' },
  { id: 'E2qihhWiSN0', title: 'Lucid Dreaming - Sleep Music', artist: '[Try Listening for 3 Minutes] Fall Asleep Fast' },
  { id: 'bCvomF85xr4', title: 'DEEP MYSTERIES', artist: 'DERRAL' },
  { id: '4D1WT7s5n6c', title: 'daisy dee- crazy', artist: '' },
  { id: 'bOFaYl_Mo3k', title: 'Love Shack (Losoul Bitshit Edit)', artist: 'The B-52\'s' },
  { id: 'TMW4lUh5tX8', title: 'Keep Control', artist: 'Sono' },
  { id: '0skigTyA4NE', title: 'Could Heaven Ever Be Like This', artist: '' },
  { id: 'peHvj5TedFI', title: 'Only Human [Ministry Of Sound]', artist: 'KH aka Four Tet' },
  { id: '7jzG2o8V5-E', title: 'Reverse Skydiving (Original Mix)', artist: 'Hot Natured feat. Anabel Englund' },
  { id: '8QHNMWgKx_c', title: 'Reckless (With Your Love)', artist: 'Azari & III' },
  { id: 'Hp4WWhbvRYk', title: 'Party Non Stop (Original) [Full Length] 2012', artist: 'Pirupa' },
  { id: 'ie14h_wtJcM', title: 'Sophie Lloyd featuring Dames Brown \'Calling Out\'', artist: '' },
  { id: 'xdYK9TCSzd4', title: 'Whitney Houston So Emotional Extended Mix', artist: '' },
  { id: 'qLAxBS0wK84', title: 'Red Light Green Light', artist: 'Half Pint' },
  { id: 'wUtLLT4ZjkI', title: 'Runaway Love (12\' Mix)', artist: 'Linda Clifford' },
  { id: '1SObQce7C78', title: 'Love Will Save The Day (Club Mix) (Extended Remix)', artist: '' },
  { id: 'byORKj3J3S4', title: 'Space Warrior', artist: 'Smith \'N Hack' },
  { id: 'XOt1WjJ8ZHw', title: 'Got Woodblock', artist: 'Cadans' },
  { id: '_1N5JWr2C2g', title: 'Muyu', artist: 'Tom Demac' },
  { id: 'T_h1Op0T2d8', title: 'Swerve 2', artist: 'Hugo Massien' },
  { id: 'RmQ0XFwBAZ8', title: 'Jungle Bill [Chicken Dive Mix]', artist: 'Yello' },
  { id: 'SjMtJbZT8FQ', title: 'Kabuki (Ritual Version)', artist: 'Young Wolf' },
  { id: 'MHFnn8ZPKJM', title: 'Use Me', artist: 'Runaway' },
  { id: 'vZlyGEBTfoE', title: 'Dirtybird Couchout 2020: Astronomar', artist: '' },
  { id: 'X_RXPOW_Mhg', title: 'DJ Matpat LIVE | CLUB MOBILE', artist: 'Acid, House, Baltimore Club, Ghettotech' },
  { id: 'tajdHgg6TF8', title: 'Eddy Grant   Time Warp', artist: '' },
  { id: '3iXW4N9z00M', title: 'The Break (Remix) Original 12 inch Version 1980', artist: 'Kat Mandu' },
  { id: 'Zjtlb7Jvg-g', title: 'Don\'t Leave Me This Way (Tamla Records 1976)', artist: 'Thelma Houston' },
  { id: 'SXabicgC-dk', title: 'flame (Mood II Swing borderline insanity dub mix) - Jive', artist: 'Crustation' },
  { id: 'f2bgs82_RcU', title: 'EL MELONCITO (TOYT105)', artist: 'FELIPE GORDAN' },
  { id: 'f20RD1eNDl0', title: 'RACHMAD PROJECT 5', artist: 'A LOT OF LOVE' },
  { id: 'G24Lm1KZX0g', title: 'HAULES BAULES "CREEPER"', artist: '' },
  { id: '8IZoR5Rmu9c', title: 'Walk The Night (Disconet Edit)', artist: 'Skatt Bros.' },
  { id: 'HivQqTtiHVw', title: 'Modern Love', artist: 'David Bowie' },
  { id: '4hPv6EuV7dM', title: 'Big Love', artist: 'Fleetwood Mac' },
  { id: 'wrUxEvKNQo4', title: 'Diana Ross The Boss (Dimitri From Paris Remix)', artist: '' },
  { id: 'pJwcng1Md1k', title: 'Stay Up (The Radio Mix)', artist: 'Party Girls' },
  { id: 'zOKyd58K710', title: 'Denkimi Shakuhachi', artist: 'Man Machine feat Zen' },
  { id: 'o-zIE5tgCG8', title: 'you got love song (c.o.m.b.i edit)', artist: 'Front page' },
  { id: 'xn_d3HkJc44', title: 'I WANT IT ALL NOW (JUSTIN VAN DER VOLGEN EDIT)', artist: 'PEGGI BLU' },
  { id: 'UcsqoPiSF5Q', title: 'Shake & Pop', artist: 'Green Velvet' },
  { id: '7OSWUZaTOLk', title: 'Houston We Have A Problem', artist: 'Genius Of Time' },
  { id: 'hO3upRBV1es', title: 'Sweet Lucy', artist: 'Raul de Souza' },
  { id: 'BvquWyzmTh0', title: 'Pump It Up (Extended Mix)', artist: 'The Black & White Brothers' },
  { id: 'xMnsJzQHQTI', title: 'DAISY\'S DANCE (SULTA SELECTS SILVER SERVICE)', artist: 'DAN SHAKE' },
  { id: 'f72C6Puv8h0', title: 'Untitled', artist: 'Paul Woolford' },
  { id: 'Zi-KtQLRuOM', title: 'I DON\'T DANCE I MAKE MONEY MOVES (PUSS)', artist: 'RD' },
  { id: 'q0sUbIWWGmw', title: 'KNEEL B4 THELMA', artist: 'BITTER END' },
  { id: 'Qa8_MYL_F5k', title: 'SOMEBODY (ROLLER RINK)', artist: 'ASQUITH' },
  { id: 'TDdlY96qS7E', title: 'We Lift Our Hands In The Sanctuary (Friday Night Live Mix)', artist: '' },
  { id: 'uUqcBwQjj4k', title: 'Oliver Cheatham, Get Down Saturday Night (Funk 1983) Full HD !', artist: '' },
  { id: 'VaVSdj38inI', title: 'lovin\' is really my game', artist: 'brainstorm' },
  { id: 'rYhK1XwELxw', title: 'WHEN YOU WAKE UP TOMORROW (BAUME LOVE EDIT)', artist: 'CANDI STATON' },
  { id: 'HlueS6hA0r8', title: 'Dreaming (Terrence Parker\'s Divine Spiritual Remix)', artist: 'Loleatta Holloway' },
  { id: 'jjDc0-mTB44', title: 'Boden Pt. 2', artist: 'Cabletoy Feat. Lipelis' },
  { id: 'UgedZlVwKSo', title: 'HANDYMAN DISCO -BAD FOLKS (MICADE\'S SO BAD MIX)', artist: '' },
  { id: 'YGBDAxCDLs4', title: 'There But for the Grace of God Go I (Original Version)', artist: 'Machine' },
  { id: 'oASmgr4IpIk', title: 'Todd Terry', artist: 'Bounce to the Beat' },
  { id: '2sngS0lPGwI', title: 'Don\'t go lose this (Main)', artist: 'Daniel Wang pres. S.D.A.P.' },
  { id: 'WFZkUAVb9Ts', title: 'Hungry Child (Paul Woolford Sunrise Mix)', artist: 'Hot Chip' },
  { id: 'XpxYssyiDI8', title: 'LTR [Axe Traxx]', artist: 'Kirk The Flirt' },
  { id: 'Qh2r6eCpigQ', title: 'Rhythm (Young Marco Fix)', artist: 'Hot Slot Machine' },
  { id: 'eXOJUbyf7Vs', title: 'All Night Passion (NOEDIT001)', artist: 'Nocturne Edits' },
  { id: 'aOBUqCIXXWY', title: 'Cybotron Cosmic Cars', artist: '' },
  { id: 'dt_BNjPCXLQ', title: 'Get On Down (Theo Parrish Re-Edit)', artist: 'The Dells' },
  { id: 'Vxe_RiZWHgE', title: 'In the Heat of the Night (Acid Mix) [Freerange]', artist: 'Da Posse' },
  { id: '_vhaY_jXENk', title: 'Hit It n Quit It', artist: 'Jamie 3:26 & Cratebug' },
  { id: 'tZsCtcYGuKQ', title: 'joi - Anthem', artist: 'N' },
  { id: 'IK1rBVOzxwY', title: 'Mr. G- It Dub', artist: '' },
  { id: 'khyqn1eg3lM', title: 'POP CORN', artist: 'MAGIC MEN' },
  { id: 'uT_AqOcodKA', title: 'How To Be A Zillionaire (Wall Street Mix)', artist: 'ABC' },
  { id: 'uOSJOKgMb1g', title: 'Saturday (SHEE Edit)', artist: 'Norma Jean' },
  { id: 'xuIAfxCUXqo', title: 'NEVER GET ENOUGH (BLTRS 015)', artist: 'JORDAN NOCTURNE' },
  { id: '4gVo2z_tYig', title: 'Burning (Hundred Flowers)', artist: 'Soundbwoy Killah' },
  { id: 'GPoZ9gzCqV0', title: 'Truth Bomb (Super Rhythm Trax)', artist: 'Chrissy' },
  { id: '9DT6VY0cAbs', title: 'SHINE ON (LETS PLAY HOUSE)', artist: 'LAROZE' },
  { id: 'FWG-JSGUfro', title: 'UNTITLED A (DISCO EDITS VOL 1) (DISC COMPANY)', artist: 'UNKNOWN ARTIST' },
  { id: 'mxFJBRJ_czI', title: 'UNTITLED B (DISCO EDITS VOL 1) (DISC COMPANY)', artist: 'UNKNOWN ARTIST' },
  { id: 'Alak6zMv9EA', title: 'FASCINATED (EDIT) (NOCTURNE EDITS 01)', artist: 'COMPANY B' },
  { id: 'Z-f040SYmg0', title: 'ANGUS (SSSS-3)', artist: 'ATLUS' },
  { id: 'smVw8QPWVYU', title: 'MADRID GROOVE (THANKYOU003)', artist: 'MADRID GROOVE' },
  { id: 'vyrhc4KyL8g', title: 'Tomorrow (Take It To Church Vol 2) (Riot Records)', artist: 'Yam Who?' },
  { id: 'fW9amKQ3SxA', title: 'MYSTERIOUS (SEMI DELICIOUS)', artist: 'DEMI RIQUISIMO' },
  { id: 'yrpHuK3r76E', title: 'TRACK B', artist: 'SECRET SQUIRRELS # 20' },
  { id: 'SOVnAIqme1s', title: 'SO GLAD (M-PLANT)', artist: 'FLOORPLAN' },
  { id: '_OeGS4IUmho', title: 'Rise & Shine (Feat. Frank Hooker) (Lumberjacks In Hell)', artist: 'Alan Dixon' },
  { id: 'kAc7ZUcVj3Y', title: 'Theme from S-Express', artist: 'S\'Express' },
  { id: 'SZZSLewPEN8', title: 'Winners (Larry Levan Demo Mix)', artist: 'Man Friday' },
  { id: 'z8jKjImRhw4', title: 'Feel Up (Larry Levan Mix)', artist: 'Grace Jones' },
  { id: 'QIxYLemNjB0', title: 'Put Your Love On The Line [Paradise Garage] 1980 Disco', artist: 'Dee Edwards' },
  { id: 'EeoklirVyFc', title: 'She Not In (Stanton Warriors Re Edit)', artist: 'Chicken Lips' },
  { id: 'EfbIq2kbXXs', title: 'Let me be your fantasy (UK Garage mix) White label', artist: 'Baby D' },
  { id: 'QYNs2t11yxQ', title: 'Girls Like Us', artist: 'B15 project' },
  { id: 'NWqrHcc6p5M', title: 'Baby You Make My Heart Sing', artist: 'Ordinary People' },
  { id: 'ok5Fepg_Lh0', title: 'What You Need...', artist: 'Soft House Company' },
  { id: 'C9EQJ3KZX-Q', title: 'Fascination- Don\'t You Think It\'s Time (TRANSFORMER MIX)', artist: '' },
  { id: 'Ut4JMeL56wQ', title: 'So Hot (Bronx Beat)', artist: 'Daniela' },
  { id: 'gppf7VxCR8Q', title: 'Miss Your Loving (Fresh Dance Mix)', artist: 'Kim Davis' },
  { id: '_5REz3KHyCA', title: 'Let The Music Play (Dub Version)', artist: 'Shannon' },
  { id: 'la0Pc4hVf_M', title: 'Work It To The Bone', artist: 'LNR' },
  { id: 'lWMAflEUwpw', title: 'Powder (Jimpster Remix)  [Garage House / Madhouse Records]', artist: 'Kerri Chandler, Jerome Sydenham' },
  { id: 'BndnjhmaJ6M', title: 'Make Me Float', artist: 'Demuja' },
  { id: 'JltD6xXNUdo', title: 'The More I Want', artist: 'Cassettes For Kids' },
  { id: 'Iut-mcepzcM', title: 'You\'re Losing Me', artist: 'DJ Ciderman' },
  { id: 'AGhNQJ0LCv0', title: 'Im Nin\'alu', artist: 'Crowd Control' },
  { id: 'JwCUq_lN-NU', title: 'Holy Water Other', artist: 'MOMA READY' },
  { id: 'DsG5Y1rfkPQ', title: 'Inside Your Love (Swales\' In Detroit Edit)', artist: '' },
  { id: 'uv11as1Rl8s', title: 'Celestial Strings', artist: 'Demuja' },
  { id: 'JE63vMzb3UE', title: 'Pick Up', artist: 'DJ Koze' },
  { id: 'jm8EDsA0iZM', title: 'Convergence', artist: 'Random Factor' },
  { id: 'iMtkOgjFAqA', title: 'Gherkin Jerks Acid Indigestion', artist: '' },
  { id: 'A7ZxRs45tTg', title: 'BICEP | GLUE', artist: '' },
  { id: 'LWJ_lUFFcSk', title: 'Lose My Breath (Four Tet Remix)', artist: 'DESTINY\'S CHILD' },
  { id: 'hXtReKC4Ako', title: 'Work It Out', artist: 'Karizma' },
  { id: 'sNbqN9TbdnE', title: 'DOMINICA | GOTTA LET YOU GO (BICEP EDIT)', artist: '' },
  { id: 'ldXZl6AX5RQ', title: 'Fell My MF Bass In Your Face (Ricochet Respek Da Ghetto Edit)', artist: 'Ricochet' },
  { id: 'LhEWybqejSo', title: 'Madonna Vogue (Bette Davis Dub)', artist: '' },
  { id: 'vXmqauitBkM', title: 'SpottieOttieDopaliscious', artist: 'Outkast' },
  { id: 'Qqzjjyj5byw', title: 'I\'m Big Freak (Patrick Adams) 1978.wmv', artist: 'Phreek' },
  { id: '7B-5MRB_zNY', title: 'Kyle Hall 35 min Boiler Room Detroit DJ Set', artist: '' },
  { id: '_DynEaqObnQ', title: 'Joy In My Life [Maurice Fulton Original Mix]', artist: '(1998) RWJ' },
  { id: 'KvqU4bk5cgs', title: 'Piano Track (Original Mix)', artist: 'Pirupa' },
  { id: 'oQzHpCSfxHo', title: 'Dance, Dance (NITE GROOVES)', artist: 'Danell Dixon' },
  { id: 'wr7PUDX40Hk', title: '\'It Makes You Forget (Itgehane) (I:Cube Remix)\'', artist: 'Peggy Gou' },
  { id: '8FqlTh5xR7A', title: 'Depeche Mode   Enjoy the Silence Ecstatic Dub', artist: '' },
  { id: 'ma6EspNy-5s', title: '& It Was U', artist: 'How To Dress Well' },
  { id: 'qLyBwBb-PW0', title: 'Fatboy Slim \'Praise You’ (Purple Disco Machine Remix)', artist: '' },
  { id: 'pKGoNBT5fCY', title: 'Gypsy Woman (Rave Yard Mix)', artist: 'Crystal Waters' },
  { id: 'Bmg_DtZ0Scw', title: 'Black Water', artist: 'Octave One feat. Ann Saunderson' },
  { id: '007pRyfJInA', title: 'Ivoire', artist: 'Folamour' },
  { id: 'pS3x93N6jNM', title: 'Question (2017)', artist: 'KH (a.k.a. Four Tet)' },
  { id: 'FCYq3_fLGcI', title: 'Man On The Run', artist: 'Fox The Fox' },
  { id: 'KfqULmaaT2w', title: 'Running - 1984', artist: 'Patti Boulaye' },
  { id: 'gI7YHZVc7mM', title: 'Let\'s Hear It for the Boy', artist: 'Deniece Williams' },
  { id: '7X3YpXiI5dM', title: 'Show Me Love', artist: 'Robin S' },
  { id: 'YuSW6Iowciw', title: 'In The Evening (Beat Box 12" Remix)', artist: 'Sheryl Lee Ralph' },
  { id: 'W-stph0EX4U', title: 'I Never Knew Love  |Made In Detroit Mix|', artist: 'Chez Damier' },
  { id: '7ZdRMyWYitQ', title: 'Future (Kenny Larkin Tension Mix)', artist: '' },
  { id: 'cayc3shETso', title: 'This Time Baby (M+M Mix)', artist: 'Jackie Moore' },
  { id: 'q0D9Zf9muTY', title: 'Lost In Music', artist: 'Gay Marvine feat. Sister Sledge' },
  { id: 'tfFjm-6cbu8', title: 'Let The Music Play', artist: 'Barry White' },
  { id: '340q3za8w4M', title: 'Better Watch Out', artist: 'Butch le Butch' },
  { id: 'O9VariHpJl8', title: 'Borderline (Butch le Butch 5am Garage Rework)', artist: 'Madonna' },
  { id: 'GlBhHpie5as', title: 'Rodeo Star', artist: 'Pardon Moi' },
  { id: 'gMbnD0xCz-M', title: 'Freedom (Kokokyri edit)', artist: 'George Michael' },
  { id: 'izO_QLjNj6M', title: 'Freedom 90 [The Reflex Edit]', artist: 'George Michael' },
  { id: 'VnnNEAr5j-A', title: 'My Sicily (Mannix 12 Inch Disco Remix)', artist: 'Walter G feat. Jorja Stefil' },
  { id: 'Iwuad20Xy2Y', title: 'Ride Like The Wind (Joey Negro Extended Disco Mix)', artist: 'Christopher Cross' },
  { id: '1fxaKVlYNCI', title: 'A Part Of You', artist: 'Cerrone' },
  { id: 'MtNKJ3wird8', title: 'ABBA: "The Visitors" Video', artist: '' },
  { id: 'lWjZyzBulSg', title: 'Precious Little Diamond (Ced ReWork)', artist: 'Fox The Fox' },
  { id: 'PQDUijLWAUI', title: 'I Wouldn\'t Change A Thing (Alex Di Ciò Re-Edit) (Soul/Nu Disco) 2016', artist: 'Coke Escovedo' }
];
